### ISSUE TITLE
NoSuchMethod exception for useEnergy inherited from RebornCore

### ISSUE THREAD

**Issue by joncooke** [CrazyB0y/PipePump#8]
MC 1.16.4
RebornCore 4.5.0
TechReborn 3.6.1

Getting the following exception at the point of placing a pump:
```
[17:54:41] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: ru.cr1zyb0y.pipevacuumpump.blocksentity.MachinePipePumpBlockEntity.useEnergy(D)D
	at ru.cr1zyb0y.pipevacuumpump.blocksentity.MachinePipePumpBlockEntity.method_16896(MachinePipePumpBlockEntity.java:56) ~[pipe_vacuum_pump-1.1.1.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:510) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:429) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
	... 5 more
```

There was a commit to the RebornCore on Oct 20th with the message:
`PowerAcceptorBlockEntity refactored. This will break dependants.`

It's likely this commit that's causing the issue, while the method actually still does exist your code (and therefore mod) probably needs to be rebuilt against the updated RebornCore.

**Comment by joncooke** [comment]
If you apply the fix in my Pull request for the RebornCore update then you still run into a new exception when the pump tries to operate.

`net.minecraft.class_148: Ticking block entity
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.AbstractMethodError: alexiil.mc.mod.pipes.blocks.TilePipeWood.tryExtract(Lnet/minecraft/class_2350;)V
        at alexiil.mc.mod.pipes.blocks.TilePipeWood.method_16896(TilePipeWood.java:574) ~[40a3fe09-2d1b-4eba-b517-4b0891ea1610.jar:?]
        at net.minecraft.class_1937.method_18471(class_1937.java:510) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:429) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
        ... 5 more`

This is pipes related now, not RebornCore.
